mysite/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
	url(r'^polls/', include('polls.urls', namespace="polls")),
    url(r'^admin/', include(admin.site.urls)),
]

polls/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^about$', views.thanks_page, name='thanks'),
    url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),
    url(r'^(?P<pk>[0-9]+)/results/$', views.ResultsView.as_view(), name='results'),
    url(r'^(?P<question_id>[0-9]+)/vote/$', views.vote, name='vote'),
]

polls/models.py
import datetime

from django.db import models
from django.utils import timezone

# Create your models here.

class Question(models.Model):
	question_text = models.CharField(max_length=200)
	pub_date = models.DateTimeField('date published')
	def __str__(self):
		return self.question_text
	def was_published_recently(self):
		now = timezone.now()
		return now - datetime.timedelta(days=1) <= self.pub_date <= now
		return self.pub_date >= timezone.now() - datetime.timedelta(days=1)
	
	was_published_recently.admin_order_field = 'pub_date'
	was_published_recently.boolean = True
	was_published_recently.short_description = 'Published recently?'
class Choice(models.Model):
	question = models.ForeignKey(Question)
	choice_text = models.CharField(max_length=200)
	vote = models.IntegerField(default=0)
	def __str__(self):
		return self.choice_text

polls/views.py
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse
from django.views import generic
from django.utils import timezone

from .models import Choice, Question


class IndexView(generic.ListView):
    template_name = 'polls/index.html'
    context_object_name = 'latest_question_list'

    def get_queryset(self):
        """Return the last five published questions."""
        return Question.objects.filter(pub_date__lte=timezone.now()).order_by('-pub_date')[:5]


class DetailView(generic.DetailView):
    model = Question
    template_name = 'polls/detail.html'
    def get_queryset(self):
    	return Question.objects.filter(pub_date__lte=timezone.now())


class ResultsView(generic.DetailView):
    model = Question
    template_name = 'polls/results.html'

def vote(request, question_id):
	p=get_object_or_404(Question, pk=question_id)
	try:
		selected_choice = p.choice_set.get(pk=request.POST['choice'])
	except (KeyError, Choice.DoesNotExist):
		#Redisplay the question voting form.
		return render(request, 'polls/detail.html',{
			'question': p,
			'error_message': "You didn't select a choice.",
			})
	else:
		selected_choice.vote +=1
		selected_choice.save()
		return HttpResponseRedirect(reverse('polls:results',args=(p.id,)))

def thanks_page(request):
	return render(request, 'polls/thanks.html')

polls/templates/polls/detail.html
<h1>{{ question.question_text }}</h1>
{% if error_message %}<p><strong>{{ error_message }}</strong>
</p>{% endif %}

<form action="{% url 'polls:vote' question.id %}" method="post">
{% csrf_token %}
{% for choice in question.choice_set.all %}
	<input type="radio" name="choice" id="choice{{forloop.counter}}" value="{{ choice.id}}"/>
	<label for="choice{{ forloop.counter}}">{{choice.choice_text}}</label><br />
{% endfor %}
<input type="submit" value="Vote" />
</form>

polls/templates/polls/index.html
{% load staticfiles %}
<!--from codecademy-->
<link href="//maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css" rel="stylesheet">
<!--from codecademy-->
<link href='http://fonts.googleapis.com/css?family=Open+Sans:400;300' rel='stylesheet' type='text/css'>
<!--bootstrap-->
<link rel="stylesheet" href="{% static 'polls/css/bootstrap.min.css' %}" />
<!--style.css-->
<link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}" />

<body>
<div clsas = "container">
<h1> <a href="{% url 'polls:index' %}">Zenon's Questionaire </a></h1>
</div>


<div class = "container">
	<!--from django tutorial-->
	{% if latest_question_list %}
		<ul class="list-group">
		{% for question in latest_question_list %}
			<li class="list-group-item"><a href="{% url 'polls:detail' question.id %}">{{question.question_text}}</a></li>
		{% endfor %}
		</ul>
	{% else %}
		<p>No polls are available.</p>
	{% endif %}

	<!-- Personal Button-->
	
	<a href="{% url 'polls:thanks' %}" class="btn btn-primary" role ="button">Thanks!</a>
	
	<!-- From Codecademy-->
	<script src="{% static '//ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js' %}"></script>

	<!-- Bootstrap-->
	<script src="{% static '//http://code.jquery.com/jquery-1.11.3.min.js' %}"></script>
	<script src="{% static 'polls/js/bootstrap.min.js' %}"></script>

	<!--app.js-->
	<script src="{% static 'polls/js/app.js'  %}"></script>
</div>
</body>

polls/templates/polls/results.html
<h1>{{ question.question_text }}</h1>

<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.vote }} vote{{ choice.vote|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'polls:detail' question.id %}">Vote again?</a>
<a href="{% url 'polls:index' %}">Back</a>

polls/templates/polls/thanks.html
<h1> Thanks! </h1>